"use strict";

const displayTask = () => {
  const container = document.createElement("div");
  container.classList.add("task");
  const titleContainer = document.createElement("div");
  titleContainer.classList.add("task-title-container");
  container.appendChild(titleContainer);
  const title = document.createElement("div");
  title.classList.add("task-title");
  title.innerHTML = `Task 1`;
  titleContainer.appendChild(title);
  const dateAndPriority = document.createElement("div");
  dateAndPriority.classList.add("date-priority");
  const dueDate = document.createElement("div");
  dueDate.innerHTML = `<span>Due:</span> Today`;
  dueDate.classList.add("due-date");
  dateAndPriority.appendChild(dueDate);
  const priority = document.createElement("div");
  priority.innerHTML = `<span>Priority:</span> High`;
  priority.classList.add("priority");
  dateAndPriority.appendChild(priority);
  container.appendChild(dateAndPriority);
  const descriptionContainer = document.createElement("div");
  descriptionContainer.classList.add('description-container');
  container.appendChild(descriptionContainer);
  const description = document.createElement('div');
  description.classList.add("description");
  description.innerHTML = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at urna sed nulla suscipit commodo vel sed est. Vestibulum pharetra tortor a arcu blandit, eget fringilla arcu tempus. Aliquam porttitor luctus mi, vel rutrum ex semper at. Consectetur adipiscing elit nunc at urna.`;
  descriptionContainer.appendChild(description);
  const subContainer = document.createElement("div");
  subContainer.classList.add("sub-container");
  const subTitle = document.createElement("div");
  subTitle.classList.add('sub-title');
  subTitle.innerHTML = `Subtasks`;
  subContainer.appendChild(subTitle);
  const subTask = document.createElement("div");
  subTask.classList.add('sub-task');
  subTask.innerHTML = `<div>Sub Task 1</div>`;
  subContainer.appendChild(subTask);
  const subTask2 = document.createElement("div");
  subTask2.classList.add('sub-task');
  subTask2.innerHTML = `<div>Sub Task 2</div>`;
  subContainer.appendChild(subTask2);
  const subNew = document.createElement("button");
  subNew.classList.add('sub-new');
  subNew.innerHTML = "+ New";
  subContainer.appendChild(subNew);
  container.appendChild(subContainer);
  const notesContainer = document.createElement("div");
  notesContainer.classList.add("notes-container");
  const notesTitle = document.createElement("div");
  notesTitle.classList.add('notes-title');
  notesTitle.innerHTML = "Notes";
  notesContainer.appendChild(notesTitle);
  const notes = document.createElement("div");
  notes.classList.add('notes');
  notes.innerHTML = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at urna sed nulla suscipit commodo vel sed est. Vestibulum pharetra tortor a arcu blandit, eget fringilla arcu tempus.`;
  notesContainer.appendChild(notes);
  container.appendChild(notesContainer);
  return container;
};

export { displayTask };
